name: Create GitHub release
on:
  push:
    branches:
      - master
      - release/*
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install Java
        uses: ./.github/actions/install-java

      - name: Build project
        run: |
          mvn clean verify
