name: Bump Dependency
on:
  workflow_dispatch:
    inputs:
      dependency:
        description: 'Version property name (e.g. jackson.version). Empty = bump everything'
        type: string
        required: false
      version:
        description: 'New version (e.g. 2.18.1)'
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install Java
        uses: ./.github/actions/install-java

      - name: Reset staging
        shell: bash
        run: |
          git checkout -B bump/${{ github.ref_name }}

      # Option A: Bump a specific dependency property if you use properties
      - name: Update Specific Dependency Version
        if: inputs.dependency != '' && inputs.version != ''
        run: |
          mvn versions:set-property -Dproperty=${{ inputs.dependency }} -DnewVersion=${{ inputs.version }}
#          mvn versions:use-dep-version -Dincludes=${{ inputs.dependency }} -DdepVersion=${{ inputs.version }}
      # Option B: Or automatically update all dependencies to their latest releases
      - name: Update All Dependencies to Latest
        if: inputs.dependency == '' || inputs.version == ''
        run: mvn versions:use-latest-releases versions:update-parent -DallowMajorUpdates=false

      - name: Configure Git
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit snapshot version
        shell: bash
        run: |
          git add pom.xml
          git commit -m "chore: bump dependency version in pom.xml"
          git push --set-upstream -f origin bump/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "chore: bump dependencies version"
          source_branch: "bump/${{ github.ref_name }}"
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
