name: Javadoc

on:
  push:
    branches:
      - master
      - feature/javadoc-action
  workflow_dispatch:

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Java
        uses: ./.github/actions/install-java

      - name: Build and generate Javadocs
        run: |
          mvn javadoc:javadoc -P release

      - name: Check generated files
        run: |
            find ./target -name "*.html" | head -20
            ls -la ./target/site/apidocs/ || echo "Directory does not exist"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs