name: prepare-next-snapshot.yml
on:
  push:
    branches:
      - feature/*
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  update-next-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Prepare Next Snapshot
        uses: ./.github/actions/prepare-next-snapshot
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          ref_name: ${{ github.ref_name }}
