name: Release with publishing to the Maven Central
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up release version
        id: release_version
        run: |
          mvn -B versions:set versions:commit -DremoveSnapshot
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Release version = $VERSION"

      - name: Set up Maven Config
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: oracle
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Publish to Maven Central
        run: mvn --batch-mode clean deploy -P release -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  create_release:
    needs:
      - publish
    uses: ./.github/workflows/create-release.yml
    with:
      release_version: ${{ needs.publish.outputs.release_version }}

  # update_next_snapshot
