name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Install Java
        uses: ./.github/actions/install-java
      - name: Publish package
        run: mvn --batch-mode deploy -P github -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

