name: release.yml
on:
  release:
    branches:
      - master
    types: [created]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Release version ${{ github.event.inputs.release_version }}!"
      - uses: actions/checkout@v5
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: oracle
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Set projects Maven version to GitHub Action GUI set version
        run: mvn versions:set "-DnewVersion=${{ github.event.inputs.release_version }}" -DgenerateBackupPoms=false
      - name: Publish package
        run: mvn --batch-mode deploy
#        run: mvn --batch-mode clean deploy -P release -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}