name: Publish snapshots to Maven Central
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Maven Config
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: oracle
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish snapshot to Maven Central
        run: mvn --batch-mode deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

