name: Release with publishing to the Maven Central
on:
  push:
    branches:
      - feature/*
permissions:
  contents: write


jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up release version
        id: release_version
        run: |
          mvn -B versions:set versions:commit -DremoveSnapshot
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Release version = ${{ steps.release_version.outputs.version }}"

  create_release:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Print next version saved in publish job
        run: |
          echo "Release version = ${{ needs.publish.outputs.release_version }}"
          #    uses: ./.github/workflows/create-release.yml
      #    with:
      #      release_version: ${{ needs.publish.outputs.release_version }}

      - name: Checkout project
        uses: actions/checkout@v5

      - name: Increment Snapshot version
        run: |
          mvn versions:set versions:commit -DnextSnapshot

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --type bool push.autoSetupRemote true
      # May use stefanzweifel/git-auto-commit-action instead with pr against master
      - name: Commit release version
        run: |
         git add pom.xml
          git commit -m "(${{ github.actor }}): Increment next development version"
          git push origin
          

