name: Publish package to GitHub Packages
on:
  push:
    branches:
      - release/*
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Install Java
        uses: ./.github/actions/install-java
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

