name: Publish snapshots to Maven Central
on:
  push:
    branches:
      - master
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Java
        uses: ./.github/actions/install-java
      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests=true

