name: test-versions.workflow
on:
  push:
    branches:
      - feature/*

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up release version
        id: next_version
        uses: ./.github/actions/get-next-version
        with:
          version_type: ${{ github.event.inputs.version_type || 'patch' }}

      - name: Get current version
        id: current_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Set projects Maven version to GitHub Action GUI set version
        if: success() && steps.current_version.outputs.version != steps.next_version.outputs.version
        run: |
          echo "Setting new version = ${{ steps.next_version.outputs.version }}"
          mvn versions:set "-DnewVersion=${{ steps.next_version.outputs.version }}" -DgenerateBackupPoms=false

#      - name: Configure Git
#        run: |
#          git config user.name "github-actions[bot]"
#          git config user.email "github-actions[bot]@users.noreply.github.com"
#          git config --type bool push.autoSetupRemote true
#
#      - name: Commit release version
#        run: |
#          git add pom.xml
#          git commit -m "Prepare release (${{ github.actor }}): ${{ steps.next_version.outputs.version }}"
#          git push origin